# Generated by Django 4.0.6 on 2022-07-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=236, verbose_name='зоголовок')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('character', models.CharField(max_length=255, verbose_name='имя персонажа')),
            ],
        ),
        migrations.CreateModel(
            name='Epizode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.CharField(max_length=400, verbose_name='серия')),
                ('desc', models.CharField(max_length=400, verbose_name='описания')),
            ],
            options={
                'verbose_name': '',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_list', models.CharField(max_length=2333, verbose_name='локация листа')),
                ('planet', models.CharField(max_length=344, verbose_name='месео проживание')),
                ('dimension', models.CharField(max_length=344, verbose_name='измерение')),
            ],
        ),
    ]
